#!/usr/bin/env bash

set -euo pipefail

confirm() {
    local message="$1"
    local response
    local attempts=0
    local max_attempts=5

    if ! [ -t 0 ]; then
        echo "Non-interactive shell detected — assuming 'no'."
        return 1
    fi

    while true; do
        read -rp "$message [y/n]: " response

        case "$response" in
            [Yy]|[Yy][Ee][Ss])
                return 0
                ;;
            [Nn]|[Nn][Oo]|"")
                return 1
                ;;
            *)
                ((attempts++))
                if (( attempts >= max_attempts )); then
                    echo "Too many invalid attempts. Aborting."
                    return 1
                fi
                echo "Please answer yes or no (y/n)."
                ;;
        esac
    done
}

path_uname() {
    stat -c '%U' "${1}"
}

path_gname() {
    stat -c '%G' "${1}"
}

path_chmod() {
    stat --format '%a' "${1}"
}

cmd_exec() {
    (( $# < 1 )) && return 1

    local -a parts=( )
    local exec_command
    if [[ "${APP_PATH_UNAME}" != "root" ]] || [[ "${APP_PATH_GNAME}" != "root" ]]; then
        parts+=( "sudo" )
        [[ "${APP_PATH_UNAME}" != "root" ]] && parts+=( "-u" "${APP_PATH_UNAME}" )
        [[ "${APP_PATH_GNAME}" != "root" ]] && parts+=( "-g" "${APP_PATH_GNAME}" )
    fi

    exec_command="${parts[*]} $*"
    ${exec_command}
}

PATH_FILE_SELF="$(realpath "${BASH_SOURCE[0]}")"
PATH_DIR_APP="$(dirname "${PATH_FILE_SELF}")"
PATH_FILE_BIN_APP="${PATH_DIR_APP}/utx"
PATH_DIR_BIN=/usr/local/bin

OS_TYPE="$(uname -s)"
OS_TYPE=${OS_TYPE,,}

if [ "${OS_TYPE}" == "darwin" ]; then
    OS_TYPE="macos"
fi

OS_ARCH="$(uname -m)"
OS_ARCH=${OS_ARCH,,}

if [ "${OS_ARCH}" == "arm64" ]; then
    OS_ARCH="aarch64"
elif [ "${OS_ARCH}" == "amd64" ]; then
    OS_ARCH="x86_64"
fi

URL_PHP_BIN="https://dl.static-php.dev/static-php-cli/bulk/php-8.4.17-cli-${OS_TYPE}-${OS_ARCH}.tar.gz"

APP_PATH_UNAME=$(path_uname "${PATH_FILE_BIN_APP}")
APP_PATH_GNAME=$(path_gname "${PATH_FILE_BIN_APP}")

install_php(){
    echo "Downloading and installing static PHP binary... Please wait."
    curl -1sSLf "${URL_PHP_BIN}" | tar -xz -C /tmp
    mv /tmp/php "${PATH_DIR_BIN}/php"
    chown root:root "${PATH_DIR_BIN}/php"
    chmod +x "${PATH_DIR_BIN}/php"
    if command -v setcap 2>&1 >/dev/null; then
      setcap "cap_net_bind_service=+ep" "${PATH_DIR_BIN}/php"
    fi
    echo "Static PHP binary installed to: ${PATH_DIR_BIN}/php"
}

install_composer(){
    echo "Installing composer... Please wait."
    curl -1sLf https://getcomposer.org/installer | "${PATH_DIR_BIN}/php" -- --install-dir="${PATH_DIR_BIN}" --filename="composer"
    chown root:root "${PATH_DIR_BIN}/composer"
    chmod +x "${PATH_DIR_BIN}/composer"
    echo "Composer installed to: ${PATH_DIR_BIN}/composer"
}