#!/usr/bin/env php
<?php

use App\Framework\Console\ConsoleApplication;

require_once getcwd() . '/vendor/autoload.php';

ConsoleApplication::boot(
        name: 'Helper',
        root: \Phar::running(false) ? \Phar::running(false) : getcwd(),
        internalStorage: \Phar::running(false) ? sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'helper-app' : null,
)->run();

exit;