#!/usr/bin/env php
<?php

use Tempest\Console\ConsoleApplication;

require_once implode(DIRECTORY_SEPARATOR, [__DIR__, 'vendor', 'autoload.php']);

\App\Services\Support::sentinel();

ConsoleApplication::boot(
        name: 'utx',
        root: __DIR__,
)->run();

exit;